name: Build Artifacts
on:
  release:
    types: [created]
  push:
    branches:
      - '**'
env:
  TAG_NAME: ${{ github.event.release.tag_name || github.ref }}

jobs:
  multiplatform_build:
    strategy:
      fail-fast: false
      matrix:
        component:
          - name: backup-daemon
            file: alpine/Dockerfile
            base: alpine
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${GITHUB_ACTOR}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Prepare Tag
        run: echo "TAG_NAME=$(echo ${TAG_NAME} | sed 's@refs/tags/@@;s@refs/heads/@@;s@/@_@g')" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          no-cache: true
          context: ${{ matrix.component.dir }}
          file: ${{ matrix.component.file }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/netcracker/${{ matrix.component.name }}:${{ env.TAG_NAME }}_${{ matrix.component.base }}
          provenance: false
